
export const STOCKS_REQUEST = 'STOCKS/STOCKS_REQUEST';
export const STOCKS_SUCCESS = 'STOCKS/STOCKS_SUCCESS';
export const STOCKS_FAILURE = 'STOCKS/STOCKS_FAILURE';
export const SET_ER_DATE = 'STOCKS/STOCKS_SET_ER_DATE';
export const UPDATE_AFTER_LOCATION_UPDATE = 'STOCKS/STOCKS_UPDATE_AFTER_LOCATION_UPDATE';
export const SET_SORTED_STOCKS = 'STOCKS/SET_SORTED_STOCKS';

export const SET_FILTER_EXPECTED_MOVE = 'STOCKS/SET_FILTER_EXPECTED_MOVE';
export const SET_FILTER_PREVIOUS_MOVE = 'STOCKS/SET_FILTER_PREVIOUS_MOVE';
export const SET_FILTER_MARKET_CAP = 'STOCKS/SET_FILTER_MARKET_CAP';
export const SET_FILTER_COMPANY_NAME = 'STOCKS/SET_FILTER_COMPANY_NAME';
export const SET_FILTER_SYMBOL = 'STOCKS/SET_FILTER_SYMBOL';

export const TRADING_DAYS_REQUEST = 'STOCKS/TRADING_DAYS_REQUEST';
export const TRADING_DAYS_SUCCESS = 'STOCKS/TRADING_DAYS_SUCCESS';
export const TRADING_DAYS_FAILURE = 'STOCKS/TRADING_DAYS_FAILURE';

export const RESET_ERROR_MESSAGE = 'STOCKS/RESET_ERROR_MESSAGE';
